name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Docker build
      uses: docker/setup-buildx-action@v3.0.0

    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
      uses: docker/login-action@v3.0.0
      with:
        # Username used to log against the Docker registry
        username: rcosta29
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
        # Specifies whether the given registry is ECR (auto, true or false)
        ecr: auto
        # Log out from the Docker registry at the end of a job
        logout: true
          
